services:
  traffic_gatherer:
    build: ./traffic_gatherer
    container_name: traffic_gatherer
    ports:
      - "9000:9000"
    volumes:
      - ./shared:/app/shared
    network_mode: "host"
    privileged: true
    restart: always

  traffic_analyzer:
    build: ./traffic_analyzer
    container_name: traffic_analyzer
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/app/shared
    # Does not need host network mode, but standard
    network_mode: "bridge"
    restart: always

  traffic_visualizer:
    build: ./traffic_visualizer
    container_name: traffic_visualizer
    ports:
      - "5000:5000"
    volumes:
      - ./shared:/app/shared
    # Does not need host network mode, but standard
    network_mode: "bridge"
    restart: always
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always